//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Contacts model class
    /// </summary>
    public partial class Contacts
    {
        public int Id { get; set; }
        public Nullable<int> CategoriesId { get; set; }
        public string Name { get; set; }
        public string SecoundName { get; set; }
        [DataType(DataType.EmailAddress, ErrorMessage ="E-mail is not valid")]
        public string Email { get; set; }
        public string Password { get; set; }
        [DataType(DataType.PhoneNumber)]
        public Nullable<long> PhoneNumber { get; set; }
        [DataType(DataType.Date, ErrorMessage ="dd-mm-rrrr")]
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
