//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contacts
    {
        public int Id { get; set; }
        public Nullable<int> CategoriesId { get; set; }
        [Required(ErrorMessage = "User Name required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "User SecoundName required")]
        public string SecoundName { get; set; }
        [Required(ErrorMessage = "User Mail required")]
        [DataType(DataType.EmailAddress, ErrorMessage ="E-mail is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "User Password required")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)\S{6,20}$", ErrorMessage = "Invalid password format, at least: 1 upper and lower case, 6 letters")]
        public string Password { get; set; }
        [Required(ErrorMessage = "User PhoneNumber required")]
        public Nullable<int> PhoneNumber { get; set; }
        [Required(ErrorMessage = "User BirthDare required")]
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
